# Generated by Django 2.0.6 on 2018-10-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_response', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saver',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
