# Generated by Django 2.0.6 on 2018-10-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_response', '0002_auto_20181025_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saver',
            name='next_destination',
            field=models.CharField(default='', max_length=100),
        ),
    ]
