# Generated by Django 2.0.6 on 2018-10-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_response', '0004_auto_20181025_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saver',
            name='is_free',
            field=models.IntegerField(default=1),
        ),
    ]
