# Generated by Django 2.0.6 on 2018-10-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_response', '0005_auto_20181025_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pickup',
            field=models.IntegerField(default=0),
        ),
    ]
