# Generated by Django 2.0.6 on 2018-10-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_response', '0006_user_pickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saver',
            name='next_destination',
            field=models.IntegerField(default=0),
        ),
    ]
