# Generated by Django 2.0.6 on 2018-10-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_response', '0007_auto_20181026_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saver',
            name='next_destination',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
