# Generated by Django 2.0.6 on 2018-10-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_response', '0008_auto_20181026_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saver',
            name='lat',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='saver',
            name='lng',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='lat',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='lng',
            field=models.CharField(default='', max_length=100),
        ),
    ]
